### PR TITLE
fix batch size not being passed down to batch2 correctly

### PR DESCRIPTION
**Pull request by sadams**

### CODE REVIEW

**Review by ovhemert — CHANGES_REQUESTED** [review]
The way it originally works is actually correct. The problem is that the property name `size` is confusing, which should be something like `options`. Maybe you'd like to adjust that in the PR?

```
function batchStream (options) {
  return batch2.obj(options)
}
```

**Comment by sadams** [comment]
> The way it originally works is actually correct

@ovhemert i'm not sure i understand. Are you saying there is no bug in the original code? If so, maybe i'm missing something, but it didn't work for me. 

What i found was this:

```javascript
// src/streams.js
function batchStream (size) {
  return batch2.obj({ size })
}
// sec/index.js
const batchStream = streams.batchStream({ size: 1 })
```
... meant that the value of the `size` argument in `batchStream` was `{size: 1}`, which meant `batch2.obj({ size })` resulted in batch2.obj being called with:

```javascript
{
  size: {
    size: 1
  }
}
```
Which meant that batch2 was splicing an array with an invalid second argument (`batchSize = {size: 1}`) rather than a number, so the resulting batch was empty: 
```javascript
// https://github.com/ovhemert/batch2/blob/master/src/batch2.js#L32
const batch = _buffer.splice(0, batchSize) // batch will be empty array always
```

**Comment by ovhemert** [comment]
> What i found was this:
> 
> ```js
> // src/streams.js
> function batchStream (size) {
>   return batch2.obj({ size })
> }
> // sec/index.js
> const batchStream = streams.batchStream({ size: 1 })
> ```

The thing is, that `batch2.obj` does expect an object as you can see [here](https://github.com/ovhemert/batch2#api). So, `batchStream` makes a correct call to `batch2`.

The problem is with `index.js`, because it calls `streams.batchStream({ size: 1 })`, which should  be `streams.batchStream(1)`. With my comment that the code works correctly i meant the call to `batch2`.

**Comment by sadams** [comment]
Ok, i think i understand now. My issue was with the statement:
> The way it originally works is actually correct

But do you agree there is a bug?

I can see now that my solution doesn't correctly pass size as part of an object (which results in it defaulting to 1 in batch2, which means it works, so i didn't see the issue). I will change this.

The original bug, however, prevented batch2 from defaulting to 1 (since size prop had a value) and so batches were coming through empty.

**Review by ovhemert — APPROVED** [review]

**Pull request merged**
